use_frameworks!

platform :ios, '8.0'

target 'PYBaseStringHandler_Example' do
  pod 'PYBaseStringHandler', :path => '../'

  target 'PYBaseStringHandler_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
